/* 
 * File:   interupt_gen_features.h
 * Author: el msria
 *
 * Created on December 19, 2023, 6:16 PM
 */

//GENERAL DEFINITION
/*
 * HERE WE JUST ENABLE OR DISABLE THE FEATURES LIKE EXTERNAL INTERUPT INTX OR ON CHANGE , PIRIOTY LEVELS FEATURE ,,,, BY SET ANY OF THEM 
 * TO (FEATURE_ENABLE) OR (FEATURE_DIASABLE)
 */

#ifndef INTERUPT_GEN_FEATURES_H
#define	INTERUPT_GEN_FEATURES_H

#define FEATURE_ENABLE 1
#define FEATURE_DIASABLE 0
#define PIRIORITY_LEVELS_ENABLE FEATURE_DIASABLE 
#define EXTERNAL_INTERUPT_INTX_ENABLE FEATURE_ENABLE
#define EXTERNAL_INTERUPT_ON_CHANGE_ENABLE FEATURE_ENABLE 
#define ADC_INTERUPT FEATURE_DIASABLE
#define TMR0_INTERUPT FEATURE_ENABLE
#define TMR1_INTERUPT FEATURE_ENABLE
#define TMR2_INTERUPT FEATURE_ENABLE
#define TMR3_INTERUPT FEATURE_ENABLE
#define CCP1_INTERUPT FEATURE_ENABLE
#define CCP2_INTERUPT FEATURE_ENABLE
#endif	/* INTERUPT_GEN_FEATURES_H */

